apiVersion: apps/v1
kind: Deployment
metadata:
  name: miweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miweb
  template:
    metadata:
      labels:
        app: miweb
    spec:
      containers:
        - name: miweb
          image: marceloalejoc/miweb:v0.0.8
          imagePullPolicy: Always
          ports:
            - containerPort: 80
