apiVersion: apps/v1
kind: Deployment
metadata:
  name: miweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miweb
  template:
    metadata:
      labels:
        app: miweb
    spec:
      containers:
        - name: miweb
          image: DOCKERHUB_USERNAME/miweb:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
