name: Deploy a Kubernetes

on:
  workflow_run:
    workflows: ["CI-CD Docker Web"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Obtener versión
        id: version
        run: |
          VERSION=$(git describe --tags --abbrev=0 || echo "latest")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Reemplazar imagen en deployment
        run: |
          sed -i "s|USER_DOCKERHUB/miweb:latest|${{ secrets.DOCKERHUB_USERNAME }}/miweb:${{ steps.version.outputs.version }}|g" k8s/deployment.yaml

      - name: Aplicar Manifiestos
        run: |
          kubectl apply -f k8s/